import { DiagnosticResult, PathogenId, WorkOrderTicket } from "@/types/sentinel";

// ============================================================================
// Curated High-Definition Agricultural Leaf Photographic Assets
// Real macro photographs of actual plant leaves infected with target pathogens.
// Zero cartoon drawings or artificial SVGs.
// ============================================================================

export const POTATO_LATE_BLIGHT_IMAGE = "/samples/potato_late_blight.jpg";
export const TOMATO_EARLY_BLIGHT_IMAGE = "/samples/tomato_early_blight.jpg";
export const CORN_RUST_IMAGE = "/samples/corn_rust.jpg";
export const APPLE_SCAB_IMAGE = "/samples/apple_scab.jpg";
export const HEALTHY_LEAF_IMAGE = "/samples/healthy_leaf.jpg";

// Backwards-compatible aliases for legacy references
export const POTATO_LATE_BLIGHT_SVG = POTATO_LATE_BLIGHT_IMAGE;
export const TOMATO_EARLY_BLIGHT_SVG = TOMATO_EARLY_BLIGHT_IMAGE;
export const CORN_RUST_SVG = CORN_RUST_IMAGE;
export const HEALTHY_LEAF_SVG = HEALTHY_LEAF_IMAGE;

// ============================================================================
// Curated Diagnostics Registry
// ============================================================================

export const SAMPLE_DIAGNOSTICS: Record<PathogenId, DiagnosticResult> = {
  potato_late_blight: {
    pathogenId: "potato_late_blight",
    commonName: "Potato Late Blight",
    scientificName: "Phytophthora infestans",
    confidence: 96.4,
    necrosisPercentage: 18.5,
    severityLevel: "CRITICAL",
    imageUrl: POTATO_LATE_BLIGHT_SVG,
    scannedAt: new Date().toISOString(),
    boundingBoxes: [
      {
        id: "box-plb-1",
        ymin: 24.0,
        xmin: 32.0,
        ymax: 58.0,
        xmax: 68.0,
        label: "Necrotic Lesion (Phytophthora)",
        confidence: 96.4,
      },
      {
        id: "box-plb-2",
        ymin: 62.0,
        xmin: 55.0,
        ymax: 82.0,
        xmax: 80.0,
        label: "Sporulation Margin",
        confidence: 92.1,
      },
    ],
    ragRetrieval: {
      queryVectorDimensions: 32,
      topMatch: {
        specimenId: "USDA-ARS-PLB-0881",
        cropSpecies: "Solanum tuberosum (Russet Burbank)",
        pathogenName: "Phytophthora infestans (Oomycete)",
        commonName: "Potato Late Blight",
        pathogenId: "potato_late_blight",
        similarityScore: 97.8,
        institutionSource: "USDA-ARS / Cornell Agricultural Extension [PLB-881]",
        diagnosticMarkers: [
          "Rapidly advancing dark water-soaked necrotic lesions (>20% surface)",
          "Pale chlorotic halo advancing along leaflet tips and margins",
          "Pinnate compound leaf geometry with ovate lateral leaflets",
          "Sporangia emergence under high humidity (>85% RH)",
        ],
      },
      candidates: [
        {
          specimenId: "USDA-ARS-PLB-0881",
          cropSpecies: "Solanum tuberosum",
          pathogenName: "Phytophthora infestans",
          commonName: "Potato Late Blight",
          pathogenId: "potato_late_blight",
          similarityScore: 97.8,
          institutionSource: "USDA-ARS [PLB-881]",
          diagnosticMarkers: ["Water-soaked dark lesions", "Chlorotic halo margin"],
        },
        {
          specimenId: "USDA-ARS-NCLB-6411",
          cropSpecies: "Zea mays",
          pathogenName: "Exserohilum turcicum",
          commonName: "Northern Corn Leaf Blight",
          pathogenId: "corn_northern_blight",
          similarityScore: 68.4,
          institutionSource: "University of Illinois [NCLB-6411]",
          diagnosticMarkers: ["Cigar-shaped lesions"],
        },
        {
          specimenId: "USDA-ARS-TEB-0422",
          cropSpecies: "Solanum lycopersicum",
          pathogenName: "Alternaria solani",
          commonName: "Tomato Early Blight",
          pathogenId: "tomato_early_blight",
          similarityScore: 42.1,
          institutionSource: "University of Florida [TEB-422]",
          diagnosticMarkers: ["Concentric target rings"],
        },
      ],
      totalAtlasSpecimensIndexed: 14200,
      retrievalLatencyMs: 38,
    },
  },
  tomato_early_blight: {
    pathogenId: "tomato_early_blight",
    commonName: "Tomato Early Blight",
    scientificName: "Alternaria solani",
    confidence: 94.1,
    necrosisPercentage: 12.8,
    severityLevel: "HIGH",
    imageUrl: TOMATO_EARLY_BLIGHT_SVG,
    scannedAt: new Date().toISOString(),
    boundingBoxes: [
      {
        id: "box-teb-1",
        ymin: 28.0,
        xmin: 33.0,
        ymax: 56.0,
        xmax: 62.0,
        label: "Concentric Target Spot",
        confidence: 94.1,
      },
      {
        id: "box-teb-2",
        ymin: 58.0,
        xmin: 42.0,
        ymax: 78.0,
        xmax: 66.0,
        label: "Secondary Alternaria Lesion",
        confidence: 91.5,
      },
    ],
    ragRetrieval: {
      queryVectorDimensions: 32,
      topMatch: {
        specimenId: "USDA-ARS-TEB-0422",
        cropSpecies: "Solanum lycopersicum (Roma Tomato)",
        pathogenName: "Alternaria solani (Ascomycete)",
        commonName: "Tomato Early Blight",
        pathogenId: "tomato_early_blight",
        similarityScore: 96.4,
        institutionSource: "University of Florida IFAS Plant Pathology [TEB-422]",
        diagnosticMarkers: [
          "Concentric alternating dark and light rings (target-board appearance)",
          "Pronounced brilliant yellow chlorotic halo surrounding lesions",
          "Deeply lobed pinnatifid foliar morphology",
          "Localized circular to oval lesions with distinct boundaries",
        ],
      },
      candidates: [
        {
          specimenId: "USDA-ARS-TEB-0422",
          cropSpecies: "Solanum lycopersicum",
          pathogenName: "Alternaria solani",
          commonName: "Tomato Early Blight",
          pathogenId: "tomato_early_blight",
          similarityScore: 96.4,
          institutionSource: "University of Florida [TEB-422]",
          diagnosticMarkers: ["Concentric rings", "Yellow chlorotic halo"],
        },
        {
          specimenId: "USDA-ARS-AS-1194",
          cropSpecies: "Malus domestica",
          pathogenName: "Venturia inaequalis",
          commonName: "Apple Scab",
          pathogenId: "apple_scab",
          similarityScore: 61.2,
          institutionSource: "Cornell Fruit Pathology [AS-1194]",
          diagnosticMarkers: ["Velvety olive-black lesion", "Serrated margin"],
        },
        {
          specimenId: "USDA-ARS-CAR-0931",
          cropSpecies: "Malus domestica",
          pathogenName: "Gymnosporangium",
          commonName: "Cedar Apple Rust",
          pathogenId: "apple_rust",
          similarityScore: 48.6,
          institutionSource: "Penn State Extension [CAR-0931]",
          diagnosticMarkers: ["Yellow-orange circular spots"],
        },
      ],
      totalAtlasSpecimensIndexed: 14200,
      retrievalLatencyMs: 42,
    },
  },
  corn_rust: {
    pathogenId: "corn_rust",
    commonName: "Corn Common Rust",
    scientificName: "Puccinia sorghi",
    confidence: 92.8,
    necrosisPercentage: 15.2,
    severityLevel: "HIGH",
    imageUrl: CORN_RUST_SVG,
    scannedAt: new Date().toISOString(),
    boundingBoxes: [
      {
        id: "box-cr-1",
        ymin: 22.0,
        xmin: 35.0,
        ymax: 46.0,
        xmax: 65.0,
        label: "Rust Pustule Streak",
        confidence: 92.8,
      },
      {
        id: "box-cr-2",
        ymin: 50.0,
        xmin: 38.0,
        ymax: 76.0,
        xmax: 68.0,
        label: "Dense Urediniospore Cluster",
        confidence: 89.6,
      },
    ],
    ragRetrieval: {
      queryVectorDimensions: 32,
      topMatch: {
        specimenId: "USDA-ARS-CCR-5104",
        cropSpecies: "Zea mays (Yellow Dent Corn)",
        pathogenName: "Puccinia sorghi (Basidiomycete)",
        commonName: "Corn Common Rust",
        pathogenId: "corn_rust",
        similarityScore: 96.0,
        institutionSource: "Purdue Extension Crop Diseases Laboratory [CCR-5104]",
        diagnosticMarkers: [
          "Elongated brick-red to golden-brown pustules arranged in parallel linear rows",
          "Monocot linear-lanceolate strap blade with parallel venation (Aspect > 2.2)",
          "Prominent midrib with bilateral leaf symmetry",
          "Eruptive powdery urediniospores scattered on upper and lower epidermis",
        ],
      },
      candidates: [
        {
          specimenId: "USDA-ARS-CCR-5104",
          cropSpecies: "Zea mays",
          pathogenName: "Puccinia sorghi",
          commonName: "Corn Common Rust",
          pathogenId: "corn_rust",
          similarityScore: 96.0,
          institutionSource: "Purdue Extension [CCR-5104]",
          diagnosticMarkers: ["Linear rust pustules", "Parallel venation"],
        },
        {
          specimenId: "USDA-ARS-WSR-2890",
          cropSpecies: "Triticum aestivum",
          pathogenName: "Puccinia striiformis",
          commonName: "Wheat Stripe Rust",
          pathogenId: "wheat_rust",
          similarityScore: 78.4,
          institutionSource: "USDA-ARS [WSR-2890]",
          diagnosticMarkers: ["Narrow pustule stripes"],
        },
        {
          specimenId: "USDA-ARS-NCLB-6012",
          cropSpecies: "Zea mays",
          pathogenName: "Exserohilum turcicum",
          commonName: "Northern Corn Leaf Blight",
          pathogenId: "corn_northern_blight",
          similarityScore: 68.5,
          institutionSource: "University of Illinois [NCLB-6012]",
          diagnosticMarkers: ["Cigar-shaped lesions", "Parallel venation"],
        },
      ],
      totalAtlasSpecimensIndexed: 14200,
      retrievalLatencyMs: 35,
    },
  },
  powdery_mildew: {
    pathogenId: "powdery_mildew",
    commonName: "Cucurbit Powdery Mildew",
    scientificName: "Podosphaera xanthii",
    confidence: 90.7,
    necrosisPercentage: 8.4,
    severityLevel: "MODERATE",
    imageUrl: POTATO_LATE_BLIGHT_SVG, // Fallback visual
    scannedAt: new Date().toISOString(),
    boundingBoxes: [
      {
        id: "box-pm-1",
        ymin: 30.0,
        xmin: 30.0,
        ymax: 65.0,
        xmax: 70.0,
        label: "Talcum Powdery Mycelium",
        confidence: 90.7,
      },
    ],
  },
  corn_northern_blight: {
    pathogenId: "corn_northern_blight",
    commonName: "Northern Corn Leaf Blight",
    scientificName: "Exserohilum turcicum",
    confidence: 94.0,
    necrosisPercentage: 16.5,
    severityLevel: "HIGH",
    imageUrl: CORN_RUST_SVG,
    scannedAt: new Date().toISOString(),
    boundingBoxes: [
      {
        id: "box-nclb-1",
        ymin: 20.0,
        xmin: 25.0,
        ymax: 75.0,
        xmax: 75.0,
        label: "Cigar-shaped Exserohilum Lesion",
        confidence: 94.0,
      },
    ],
  },
  wheat_rust: {
    pathogenId: "wheat_rust",
    commonName: "Wheat Stripe Rust",
    scientificName: "Puccinia striiformis",
    confidence: 93.8,
    necrosisPercentage: 13.5,
    severityLevel: "HIGH",
    imageUrl: CORN_RUST_SVG,
    scannedAt: new Date().toISOString(),
    boundingBoxes: [
      {
        id: "box-wr-1",
        ymin: 15.0,
        xmin: 35.0,
        ymax: 85.0,
        xmax: 65.0,
        label: "Linear Stripe Rust Uredinia",
        confidence: 93.8,
      },
    ],
  },
  apple_scab: {
    pathogenId: "apple_scab",
    commonName: "Apple Scab",
    scientificName: "Venturia inaequalis (Malus domestica)",
    confidence: 96.8,
    necrosisPercentage: 22.4,
    severityLevel: "HIGH",
    imageUrl: APPLE_SCAB_IMAGE,
    scannedAt: new Date().toISOString(),
    boundingBoxes: [
      {
        id: "box-as-1",
        ymin: 24.0,
        xmin: 22.0,
        ymax: 68.0,
        xmax: 78.0,
        label: "Venturia inaequalis Scab: 96.8%",
        confidence: 96.8,
      },
      {
        id: "box-as-2",
        ymin: 38.0,
        xmin: 42.0,
        ymax: 56.0,
        xmax: 64.0,
        label: "Olive-Black Velvety Conidiophores",
        confidence: 94.2,
      },
    ],
    ragRetrieval: {
      queryVectorDimensions: 32,
      topMatch: {
        specimenId: "USDA-ARS-AS-1194",
        cropSpecies: "Malus domestica (Honeycrisp Apple)",
        pathogenName: "Venturia inaequalis (Ascomycete)",
        commonName: "Apple Scab",
        pathogenId: "apple_scab",
        similarityScore: 97.4,
        institutionSource: "Cornell University Fruit Pathology Laboratory [AS-1194]",
        diagnosticMarkers: [
          "Dark olive-green to velvety brown-black irregular foliar lesions",
          "Broadleaf serrated margin foliar silhouette with palmate/pinnate venation",
          "Sub-cuticular stroma with conidiophore eruption",
          "Secondary chlorotic halos expanding along leaf margins",
        ],
      },
      candidates: [
        {
          specimenId: "USDA-ARS-AS-1194",
          cropSpecies: "Malus domestica",
          pathogenName: "Venturia inaequalis",
          commonName: "Apple Scab",
          pathogenId: "apple_scab",
          similarityScore: 97.4,
          institutionSource: "Cornell Fruit Pathology [AS-1194]",
          diagnosticMarkers: ["Velvety olive-black lesion", "Serrated margin"],
        },
        {
          specimenId: "USDA-ARS-CAR-0931",
          cropSpecies: "Malus domestica",
          pathogenName: "Gymnosporangium juniperi-virginianae",
          commonName: "Cedar Apple Rust",
          pathogenId: "apple_rust",
          similarityScore: 54.2,
          institutionSource: "Penn State Extension [CAR-0931]",
          diagnosticMarkers: ["Yellow-orange aeciospores"],
        },
        {
          specimenId: "USDA-ARS-TEB-0422",
          cropSpecies: "Solanum lycopersicum",
          pathogenName: "Alternaria solani",
          commonName: "Tomato Early Blight",
          pathogenId: "tomato_early_blight",
          similarityScore: 38.6,
          institutionSource: "University of Florida [TEB-422]",
          diagnosticMarkers: ["Concentric rings"],
        },
      ],
      totalAtlasSpecimensIndexed: 14200,
      retrievalLatencyMs: 39,
    },
  },
  apple_rust: {
    pathogenId: "apple_rust",
    commonName: "Cedar Apple Rust",
    scientificName: "Gymnosporangium juniperi-virginianae",
    confidence: 94.6,
    necrosisPercentage: 14.2,
    severityLevel: "HIGH",
    imageUrl: APPLE_SCAB_IMAGE,
    scannedAt: new Date().toISOString(),
    boundingBoxes: [
      {
        id: "box-ar-1",
        ymin: 25.0,
        xmin: 25.0,
        ymax: 75.0,
        xmax: 75.0,
        label: "Gymnosporangium Rust Aecium: 94.6%",
        confidence: 94.6,
      },
    ],
  },
  non_plant_detected: {
    pathogenId: "non_plant_detected",
    commonName: "Non-Crop Image Detected",
    scientificName: "No Foliar Tissue Found (Human / Non-Agricultural Subject)",
    confidence: 0.0,
    necrosisPercentage: 0.0,
    severityLevel: "LOW",
    imageUrl: HEALTHY_LEAF_IMAGE,
    scannedAt: new Date().toISOString(),
    boundingBoxes: [
      {
        id: "box-non-plant",
        ymin: 10.0,
        xmin: 10.0,
        ymax: 90.0,
        xmax: 90.0,
        label: "INVALID: Non-Plant Subject (0% Crop Tissue)",
        confidence: 0.0,
      },
    ],
  },
  healthy: {
    pathogenId: "healthy",
    commonName: "Healthy Crop Foliage",
    scientificName: "Solanum tuberosum (Healthy)",
    confidence: 99.2,
    necrosisPercentage: 0.0,
    severityLevel: "LOW",
    imageUrl: HEALTHY_LEAF_IMAGE,
    scannedAt: new Date().toISOString(),
    boundingBoxes: [
      {
        id: "box-h-1",
        ymin: 15.0,
        xmin: 20.0,
        ymax: 85.0,
        xmax: 80.0,
        label: "Vigorous Vascular Foliage (0% Necrosis)",
        confidence: 99.2,
      },
    ],
    ragRetrieval: {
      queryVectorDimensions: 32,
      topMatch: {
        specimenId: "USDA-ARS-HL-0012",
        cropSpecies: "Solanum tuberosum (Healthy Control)",
        pathogenName: "Zero Pathogen Detected",
        commonName: "Healthy Crop Foliage",
        pathogenId: "healthy",
        similarityScore: 99.4,
        institutionSource: "USDA-ARS Agricultural Research Center [HL-0012]",
        diagnosticMarkers: [
          "Uniform high chlorophyll reflectance (ExG > 45, GLI > 0.22)",
          "Pristine vascular epidermis free of necrotic or chlorotic lesions",
          "Intact leaf lamina and leaf margins",
          "Baseline physiological vigor index: 99.2%",
        ],
      },
      candidates: [
        {
          specimenId: "USDA-ARS-HL-0012",
          cropSpecies: "Solanum tuberosum",
          pathogenName: "Healthy Control",
          commonName: "Healthy Crop Foliage",
          pathogenId: "healthy",
          similarityScore: 99.4,
          institutionSource: "USDA-ARS [HL-0012]",
          diagnosticMarkers: ["Uniform chlorophyll", "Zero necrotic lesions"],
        },
      ],
      totalAtlasSpecimensIndexed: 14200,
      retrievalLatencyMs: 28,
    },
  },
};

// ============================================================================
// Standard Mock Work Order Ticket (Contractual fixture for Dev B)
// ============================================================================

export const MOCK_WORK_ORDER: WorkOrderTicket = {
  ticketId: "WO-2026-0941",
  timestamp: new Date().toISOString(),
  farmName: "Oak Ridge Commercial Farm",
  sectorId: "Sector 4B - North Quadrant",
  acreage: 140,
  diagnostic: SAMPLE_DIAGNOSTICS.potato_late_blight,
  weather: {
    temperatureC: 19.4,
    relativeHumidity: 88,
    windSpeedMph: 6.2,
    condition: "High Humidity / High Spore Velocity",
    sporeSpreadRisk: "SEVERE",
    wallinIndex: 3,
    summary: "88% RH and 19.4°C create optimal fungal germination within 48 hours.",
  },
  prescription: {
    chemicalName: "Chlorothalonil 720 SC",
    epaRegNumber: "EPA Reg. #50534-188",
    activeIngredient: "Chlorothalonil (54.0% w/w)",
    dosagePerAcre: "1.5 pt / acre",
    waterVolumePerAcre: "20 gal / acre",
    safeToSpray: true,
    windBufferNotice: "Wind speed 6.2 mph (< 10 mph EPA limit). Compliant with aquatic buffer zones.",
    totalChemicalVolume: "26.2 Gallons",
    estimatedChemicalCostUsd: 2140,
  },
  estimatedCropSavedUsd: 32400,
  chemicalSavingsPct: 34,
};
